# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wordcount.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wordcount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwordcount.proto\x12\twordcount\"P\n\tTextChunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08\x62\x61tch_id\x18\x04 \x01(\x05\"\x83\x02\n\x0fWordCountResult\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_words\x18\x02 \x01(\x03\x12\x14\n\x0cunique_words\x18\x03 \x01(\x03\x12?\n\x0bword_counts\x18\x04 \x03(\x0b\x32*.wordcount.WordCountResult.WordCountsEntry\x12\x17\n\x0fprocessing_time\x18\x05 \x01(\x01\x12\x0f\n\x07success\x18\x06 \x01(\x08\x12\x15\n\rerror_message\x18\x07 \x01(\t\x1a\x31\n\x0fWordCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"\"\n\rHealthRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"d\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x18\n\x10processed_chunks\x18\x03 \x01(\x03\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x01\x32\xde\x01\n\x10WordCountService\x12>\n\nCountWords\x12\x14.wordcount.TextChunk\x1a\x1a.wordcount.WordCountResult\x12\x46\n\x10\x43ountWordsStream\x12\x14.wordcount.TextChunk\x1a\x1a.wordcount.WordCountResult(\x01\x12\x42\n\x0bHealthCheck\x12\x18.wordcount.HealthRequest\x1a\x19.wordcount.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wordcount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCOUNTRESULT_WORDCOUNTSENTRY']._loaded_options = None
  _globals['_WORDCOUNTRESULT_WORDCOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_TEXTCHUNK']._serialized_start=30
  _globals['_TEXTCHUNK']._serialized_end=110
  _globals['_WORDCOUNTRESULT']._serialized_start=113
  _globals['_WORDCOUNTRESULT']._serialized_end=372
  _globals['_WORDCOUNTRESULT_WORDCOUNTSENTRY']._serialized_start=323
  _globals['_WORDCOUNTRESULT_WORDCOUNTSENTRY']._serialized_end=372
  _globals['_HEALTHREQUEST']._serialized_start=374
  _globals['_HEALTHREQUEST']._serialized_end=408
  _globals['_HEALTHRESPONSE']._serialized_start=410
  _globals['_HEALTHRESPONSE']._serialized_end=510
  _globals['_WORDCOUNTSERVICE']._serialized_start=513
  _globals['_WORDCOUNTSERVICE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
