#!/usr/bin/env python3
"""
gRPC Word Count Server
Phase 3 Bonus: Streaming Integration

This server exposes word counting functionality via gRPC,
allowing Spark Structured Streaming to call it for each micro-batch.
"""

import grpc
from concurrent import futures
import time
import logging
from collections import Counter
import re

# Import generated protobuf code (will be generated from .proto file)
# These will be generated by: python -m grpc_tools.protoc
import wordcount_pb2
import wordcount_pb2_grpc

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class WordCountServicer(wordcount_pb2_grpc.WordCountServiceServicer):
    """Implementation of WordCountService gRPC service"""
    
    def __init__(self):
        self.start_time = time.time()
        self.processed_chunks = 0
        self.version = "1.0.0"
        logger.info(f"WordCountService v{self.version} initialized")
    
    def count_words_in_text(self, text):
        """
        Core word counting logic
        
        Args:
            text (str): Input text to process
            
        Returns:
            tuple: (total_words, unique_words, word_counts_dict)
        """
        # Remove punctuation and convert to lowercase
        text = text.lower()
        text = re.sub(r'[^\w\s]', '', text)
        
        # Split into words
        words = text.split()
        
        # Count occurrences
        word_counts = Counter(words)
        
        total_words = len(words)
        unique_words = len(word_counts)
        
        return total_words, unique_words, dict(word_counts)
    
    def CountWords(self, request, context):
        """
        Process a single text chunk and return word counts
        
        Args:
            request: TextChunk message
            context: gRPC context
            
        Returns:
            WordCountResult message
        """
        start_time = time.time()
        
        try:
            logger.info(f"Processing chunk: {request.chunk_id} from batch: {request.batch_id}")
            
            # Perform word counting
            total_words, unique_words, word_counts = self.count_words_in_text(request.text)
            
            processing_time = time.time() - start_time
            self.processed_chunks += 1
            
            logger.info(
                f"Chunk {request.chunk_id}: {total_words} total words, "
                f"{unique_words} unique, processed in {processing_time:.3f}s"
            )
            
            # Build response
            response = wordcount_pb2.WordCountResult(
                chunk_id=request.chunk_id,
                total_words=total_words,
                unique_words=unique_words,
                word_counts=word_counts,
                processing_time=processing_time,
                success=True,
                error_message=""
            )
            
            return response
            
        except Exception as e:
            logger.error(f"Error processing chunk {request.chunk_id}: {e}")
            
            processing_time = time.time() - start_time
            
            return wordcount_pb2.WordCountResult(
                chunk_id=request.chunk_id,
                total_words=0,
                unique_words=0,
                word_counts={},
                processing_time=processing_time,
                success=False,
                error_message=str(e)
            )
    
    def CountWordsStream(self, request_iterator, context):
        """
        Process a stream of text chunks and return aggregated results
        
        Args:
            request_iterator: Iterator of TextChunk messages
            context: gRPC context
            
        Returns:
            WordCountResult message (aggregated)
        """
        start_time = time.time()
        
        try:
            total_words_all = 0
            all_word_counts = Counter()
            chunk_count = 0
            
            for request in request_iterator:
                logger.info(f"Stream processing chunk: {request.chunk_id}")
                
                # Process each chunk
                total_words, unique_words, word_counts = self.count_words_in_text(request.text)
                
                # Aggregate results
                total_words_all += total_words
                all_word_counts.update(word_counts)
                chunk_count += 1
                self.processed_chunks += 1
            
            processing_time = time.time() - start_time
            unique_words_all = len(all_word_counts)
            
            logger.info(
                f"Stream complete: {chunk_count} chunks, {total_words_all} total words, "
                f"{unique_words_all} unique, processed in {processing_time:.3f}s"
            )
            
            return wordcount_pb2.WordCountResult(
                chunk_id=f"stream_{chunk_count}_chunks",
                total_words=total_words_all,
                unique_words=unique_words_all,
                word_counts=dict(all_word_counts),
                processing_time=processing_time,
                success=True,
                error_message=""
            )
            
        except Exception as e:
            logger.error(f"Error processing stream: {e}")
            
            processing_time = time.time() - start_time
            
            return wordcount_pb2.WordCountResult(
                chunk_id="stream_error",
                total_words=0,
                unique_words=0,
                word_counts={},
                processing_time=processing_time,
                success=False,
                error_message=str(e)
            )
    
    def HealthCheck(self, request, context):
        """
        Health check endpoint
        
        Args:
            request: HealthRequest message
            context: gRPC context
            
        Returns:
            HealthResponse message
        """
        uptime = time.time() - self.start_time
        
        logger.debug(f"Health check from client: {request.client_id}")
        
        return wordcount_pb2.HealthResponse(
            healthy=True,
            version=self.version,
            processed_chunks=self.processed_chunks,
            uptime_seconds=uptime
        )


def serve(port=50051, max_workers=10):
    """
    Start the gRPC server
    
    Args:
        port (int): Port to listen on
        max_workers (int): Maximum number of worker threads
    """
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=max_workers))
    
    # Add service to server
    wordcount_pb2_grpc.add_WordCountServiceServicer_to_server(
        WordCountServicer(), server
    )
    
    # Bind to port
    server.add_insecure_port(f'[::]:{port}')
    
    logger.info(f"Starting gRPC WordCount Server on port {port} with {max_workers} workers...")
    server.start()
    logger.info(f"Server ready to accept connections")
    
    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        logger.info("Shutting down server...")
        server.stop(0)


if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='gRPC Word Count Server')
    parser.add_argument('--port', type=int, default=50051, help='Port to listen on')
    parser.add_argument('--workers', type=int, default=10, help='Number of worker threads')
    
    args = parser.parse_args()
    
    serve(port=args.port, max_workers=args.workers)
